// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrkunmckxluoeacqwobk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFya3VubWNreGx1b2VhY3F3b2JrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNDE5NDksImV4cCI6MjA2OTgxNzk0OX0.eGzqJVZqtGEKwqKUXDiIRlBx0h6xH5pmGTQQS3mqRSQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});